# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins:
  - jekyll-remote-theme
  - jekyll-github-metadata
  - jekyll-feed

# Permalinks
permalink:        pretty

# Setup
title:            Tom Tolleson
tagline:          'Tom Tolleson'
description:      'Portfolio of engineering and data projects by Tom Tolleson. Showcasing Oracle Cloud Infrastructure implementations, clinical trial data management systems, and technical project management expertise.'
url:              https://tomtolleson.github.io

author:
  name:           'Tom Tolleson'
  url:            http://tomtolleson.github.io

paginate:         2
google_analytics: 'UA-114897373-5'
bing_seo:		  
emailme:          tomtolleson@gmail.com

gems:             [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

github:
  repo:           https://github.com/tomtolleson/tomtolleson.github.io

tags:

github_username:  TomTolleson
facebook_username: thomas.tolleson
linkedin_username: TomTolleson

github_token: YOUR_GITHUB_TOKEN


